<?php if (Mage::helper('occ')->isEnabled() && Mage::helper('occ')->allowCustomerGroup()): ?>
<!-- occ billing/shipping info -->
<div class="occ-customer-info" id="occ-customer-info">	

	<div id="occ-customer-login" <?php if ($this->isCustomerLoggedIn()): ?>style="display:none;"<?php endif; ?>>	
    	<div class="buttons-set" id="login-buttons-container">
			<a href="javascript:void(0);" onClick="occLogin.loadLoginPopup();"><?php echo $this->__('Log In to use One Click Checkout') ?></a>	

			<span class="please-wait" id="login-please-wait" style="display:none;">
    			<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Please wait...') ?>" title="<?php echo $this->__('Please wait...') ?>" class="v-middle" /> <?php echo $this->__('Please wait...') ?>
    		</span>
    	</div>
		<script type="text/javascript">
		//<![CDATA[
		var occLogin = new OccLogin({
			login: '<?php echo $this->getUrl('occ/index/login'); ?>',
			post_login: '<?php echo $this->getUrl('occ/index/loginPost'); ?>',
			logout: '<?php echo $this->helper('customer')->getLogoutUrl(); ?>',
			logout_text: '<?php echo $this->helper('customer')->__('Log Out'); ?>',
			failure: '<?php echo $this->helper('core/url')->getCurrentUrl(); ?>'
		});
		//]]>
		</script>
	</div>
	
	<div id="occ-customer-address" <?php if (!$this->isCustomerLoggedIn()): ?>style="display:none;"<?php endif; ?>>	
		<!-- load scripts -->
		<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout.js') ?>"></script>
		
		<input type="hidden" id="occ_default_billing" value="<?php echo $this->getDefaultAddressId('billing'); ?>" />
		<input type="hidden" id="occ_default_shipping" value="<?php echo $this->getDefaultAddressId('shipping'); ?>" />		
		<ul>
		    <li class="wide">			
		    	<label for="billing-address-select" class="required"><em>*</em><?php echo $this->__('Select a billing address or enter a new address.') ?></label>	
		    	<div class="input-box" id="occ-billing-address"><?php echo $this->getAddressesHtmlSelect('billing') ?></div>    	    			
		    </li>		
		    <?php if ($this->loadShippingAddress()): ?>
		    <li class="wide">			  
		    	<label for="shipping-address-select" class="required"><em>*</em><?php echo $this->__('Select a shipping address or enter a new address.') ?></label>			  
		    	<div class="input-box" id="occ-shipping-address"><?php echo $this->getAddressesHtmlSelect('shipping') ?></div>		   
		    </li>	
		    <?php endif; ?>
		</ul>	
		<div class="buttons-set" id="customer-info-buttons-container">
    	    <button type="button" title="<?php echo $this->__('One Click Checkout') ?>" class="button" onclick="occAddress.initOcc(<?php echo $this->isAwAjaxCartEnabled; ?>)"><span><span><?php echo $this->__('One Click Checkout') ?></span></span></button>
    	    <span class="please-wait" id="customer-info-please-wait" style="display:none;">
    	        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Please wait…') ?>" title="<?php echo $this->__('Please wait...') ?>" class="v-middle" /> <?php echo $this->__('Please wait...') ?>
    	    </span>
    	</div>	
		<?php $this->setRedirectUrl(); ?>
		<script type="text/javascript">
		//<![CDATA[
		var occAddress = new OccAddress({
			initialize: '<?php echo $this->getInitUrl(); ?>',
			address: '<?php echo $this->getUrl('occ/index/address'); ?>',
			save_address: '<?php echo Mage::getUrl('occ/index/saveAddress'); ?>',
			failure: '<?php echo $this->helper('core/url')->getCurrentUrl(); ?>'
		});
		//]]>
		</script>
	</div>
	
</div>
<?php endif; ?>