<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Productquestions
 * @version    1.5.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 */
?>
<?php
$questions = $this->_collection;
?>
<div class="productquestions-container">

    <label><?php echo $questions->getSize().$this->__(' Questions & ').$questions->getSize().$this->__(' Answers') ?></label>

    <?php if ($questions->getSize()): ?>
        <?php echo $this->getChildHtml('productquestions_sorter'); ?>
        <?php if ($this->getShowPager())
            echo $this->getChildHtml('productquestions_pager'); ?>

        <ul>
            <?php foreach ($questions->getItems() as $q): ?>
                <a name="<?php echo $q->getId() ?>"> </a>
                <li class="record"><?php echo $this->__('From') ?> <b><?php echo $q->getQuestionAuthorName() ?></b> at <span class="date"><?php echo $this->formatDate($q->getQuestionDate()) ?> <?php echo $this->formatTime($q->getQuestionDate()) ?></span>
                    <ul >
                        <li class="question"><?php echo nl2br(htmlentities($q->getQuestionText(), null, 'UTF-8')) ?></li>
                        <li class="reply"><em><?php echo AW_Productquestions_Helper_Data::parseURLsIntoLinks($q->getQuestionReplyText()) ?></em></li>
                        <?php if ($this->getVotingAllowed() && !$q->IsVoted()): ?>
                            <li class="helpfulness"><?php echo $this->__('Do you find this question helpful?'); ?>&nbsp;
                                <strong>
                                    <a style="color: green; cursor:pointer;" onclick="setLocation('<?php echo $this->getUrl('productquestions/index/vote', array('id' => $q->getId(), 'value' => 1)) ?>')"><?php echo $this->__('Yes') ?></a>
                                </strong>
                                &nbsp;
                                <strong>
                                    <a style="color: red; cursor:pointer;" onclick="setLocation('<?php echo $this->getUrl('productquestions/index/vote', array('id' => $q->getId(), 'value' => 0)) ?>')"><?php echo $this->__('No') ?></a>
                                </strong>
                            </li>
                        <?php endif; ?>
                    </ul>
                </li>
            <?php endforeach; ?> 
        </ul>
    <?php else: ?>
        <p><?php echo $this->__('No questions asked yet'); ?></p>
    <?php endif; ?>

    <?php echo $this->getChildHtml('productquestions_form'); ?>
    <?php if (Mage::registry('awpq_controller')): ?>
        <a href="<?php echo $this->getProduct()->getProductUrl(); ?>">  <?php echo $this->__('Back to the product page'); ?></a>
    <?php endif; ?>
</div>