<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Productquestions
 * @version    1.5.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 */
?>
<?php
$questionCount = $this->getQuestionCount();
?>
<div>
<?php if (AW_Productquestions_Helper_Data::checkIfGuestsAllowed()): ?>
        <?php if ($questionCount): ?>
            <a href="<?php echo $this->getQuestionsPageUrl() ?>"><?php echo $this->__('Ask a question (%d)', $questionCount); ?></a>
        <?php else: ?>
            <a href="<?php echo $this->getQuestionsPageUrl() ?>"><?php echo $this->__('Be the first to ask about this product'); ?></a>
        <?php endif; ?>
    <?php else: ?>
        <?php if ($questionCount): ?>
            <a href="<?php echo $this->getQuestionsPageUrl() ?>"><?php echo $this->__('View questions (%d)<br />', $questionCount) ?></a>
        <?php else: ?>
            <?php echo Mage::helper('productquestions')->getPleaseRegisterMessage(); ?>
        <?php endif; ?>
    <?php endif; ?>
</div>