<?php
$themeHelper = Mage::helper('athlete');
$colorHelper = Mage::helper('athlete/color');
$layoutHelper = Mage::helper('athlete/layout');
$imgHelper = Mage::helper('athlete/image');
$imgHelper->init( $_store->getId() );
$appearance = $themeHelper->getCfg('','athlete_appearance', $_store->getId());
$slideshow = $themeHelper->getCfg('','athleteslideshow', $_store->getId());
if ( $appearance['main']['color'] == '' ) {
	$appearance['main']['color'] = '#ffe51e';
}
if ( $appearance['main']['button_bg_color'] == '' ) {
	$appearance['main']['button_bg_color'] = $appearance['main']['color'];
}
if ( $appearance['content_banners']['link_bg'] == '' ) {
	$appearance['content_banners']['link_bg'] = $appearance['main']['color'];
}
if ( $appearance['banners_slider']['text_bg_hover_color'] == '' ) {
	$appearance['banners_slider']['text_bg_hover_color'] = $appearance['main']['color'];
}
if ( $appearance['banners_slider']['link_bg'] == '' ) {
	$appearance['banners_slider']['link_bg'] = $appearance['main']['color'];
}
if ( $appearance['pager']['pager_dropdown_link_hover_bg'] == '' ) {
	$appearance['pager']['pager_dropdown_link_hover_bg'] = $appearance['main']['color'];
}
if ( $appearance['slideshow']['timeline'] == '' ) {
	$appearance['slideshow']['timeline'] = $appearance['main']['color'];
}
if ( $appearance['slideshow']['link_bg'] == '' ) {
	$appearance['slideshow']['link_bg'] = $appearance['main']['color'];
}
if ( $appearance['product_info']['tab_bg_hover_color'] == '' ) {
	$appearance['product_info']['tab_bg_hover_color'] = $appearance['main']['color'];
}

//grid dimensions
$dimensions = array(960, 740, 426, 300);
//main image
list($imgX, $imgY) = $imgHelper->getMainSize();
//thumbs
list($thumbX, $thumbY) = $imgHelper->getThumbSize();
?>
/******************************************************************************************/
/*************************** DO NOT EDIT THIS FILE ( v1.4 ) *******************************/
/******************************************************************************************/
<?php if ($appearance['main']['enable_font'] == 1 && !empty($appearance['main']['font']) ) : ?>
/** Theme Font **/
.theme_font,
.main ul.messages,
.product-options dt label, .product-options dl.last ul.options-list .label,
.slide-title .text, .slide-title .link,
button.button span,
.header-cart .summary,
.header-cart .header-dropdown .subtotal,
	.footer .info-content h1,.footer .info-content h2,.footer .info-content h3,.footer .info-content h4,.footer .info-content h5,.footer .info-content h6,
.footer .newsletter .title,
.footer .athlete_footer_connect .title,
.athlete_footer_customer_service,
.header-cart .header-dropdown .sub-total,
#nav > li > a, #nav ul.level0 li > a, .nav-top-title a,
.content-banner .banner, .content-banner .banner a,
.text-container .text,
.nav-top-title,
.page-title h1, .opc .step h3, .opc .step-title .number, .opc .step-title h2, .block .block-title, .block-compare h3,
.block_shipping .shipping > h2, .block_coupon  .discount > h2, .block_totals #shopping-cart-totals-table tfoot strong,
p.back-link a,
.data-table .product-name, .data-table .cart-price,
.block .actions a,
.block-poll	.block-subtitle:before,
.std h1, .std h2, .std h3, .std h4,.std h5, .std h6, 
.std .h1, .std .h2, .std .h3, .std .h4,.std .h5, .std .h6,
.std .data-table tbody  th,
.category-products .product-name, .category-products .price-box,
.new-label, .sale-label,
.products-list .link-wishlist, .products-list .link-compare,
.product-view .product-category-title h3, .product-name h1,
.product-shop .add-to-links a,
.dedicated-review-box .average-rating strong,
.dedicated-review-box ol.reviews-list li .review-title,
.add-review h2, .add-review h4,
.product-tabs a,
.product-tabs-container h2.tab-heading a,
.product-view .box-tags .form-add label,
.price-box .price,
.title-container h3,
.category-banner-container .text-container a, .cms-banner.cms-banner-big-link .link, ul.custom-menu li a, .block-login h2,
.blog-title h1, .aw-blog-read-more, .postTitle h1,.commentDetails h4.username,
.blog-date, .postTitle h2 { font-family:"<?php echo $appearance['main']['font']; ?>", Arial, sans-serif; letter-spacing:-1px;}

/* letter spacing -2px */
	.text-container .text, .block-login .block-title, .title-container h3 	{ letter-spacing:-2px;}
	.product-view .price-box-wrap .price-box .price { letter-spacing:-2px;}
	
/* letter spacing -3px */

/* letter spacing -4px */
	.slide-title .text, .page-title h1, .product-slider-container-big .title-container h3, .product-view .product-category-title h3, .blog-title h1, .postTitle h1 { letter-spacing:-4px;}


	.new-label, .sale-label, .block .actions a.btn-clear { letter-spacing:inherit;}

<?php endif; ?>
<?php if ( $appearance['main']['color'] != '' ) : ?>
/** Theme Color **/
	.logo-container,
	.header-cart .summary,
	.header .top-links a:hover,
	.footer .info-content a:hover,
	a.social-icon,
	.header a.btn-edit:hover, .content-container a.btn-edit:hover,
	.header a.btn-remove:hover, .content-container a.btn-remove:hover,
	.header .form-search button.button span,
	.header .form-search button.button:hover span,
	.header-currency:hover, .header-language:hover,
	#nav>li>a:hover,
	#nav>li.over>a,
	#nav>li.active>a,
	#nav>li.parent>a:hover:before,
	#nav>li.parent.over>a:before,
	.nav-top-title:hover a,
	.nav-top-title div.icon span,
	.product-view .product-img-box .zoom .btn-zoom-out:hover,
	.product-view .product-img-box .zoom .btn-zoom-in:hover,
	.opc .allow:hover .step-title,
	.opc .allow.active .step-title .number,
	.opc .allow.active:hover .step-title .number,
	
	p.back-link a,
	.block .actions a,
	.block-wishlist .link-cart:hover,
	.block-progress dt a,
	.sorter a.sort-by-arrow:hover,
	.view-mode a.grid:hover, .view-mode strong.grid, .view-mode a.list:hover, .view-mode strong.list,
	.pager .pages li a:hover, .pager .pages li.current,
	.pager .pages li a.previous :hover, .pager .pages li a.next:hover,
	.over .toolbar-title,
	.toolbar-dropdown ul li a:hover, .toolbar-dropdown ul li.selected a,
	.products-grid .actions li button.button:hover, .products-grid .actions .add-to-links .link-wishlist:hover,
	.products-grid .actions .add-to-links .link-compare:hover,
	.add-review .rating-radio.active,
	.product-tabs li.active a,
	.product-tabs a:hover,
	.product-tabs-container h2.tab-heading:hover,
	.product-tabs-container h2.active a,
	.product-tabs-container h2.active a:hover,
	.product-tags li a:hover,
	#toTop { background-color:<?php echo $appearance['main']['color']; ?>}

	
/* a:hover */
	.products-grid li.item.hover .product-hover .animate-me .price { color:<?php echo $appearance['main']['color']; ?>}

	.block,
	.header-currency:hover .header-switch-trigger:after,
	.header-language:hover .header-switch-trigger:after {border-top-color:<?php echo $appearance['main']['color']; ?>;}

	.theme_bg_color{ background-color:<?php echo $appearance['main']['color']; ?>}
	.theme_border_color{ border-color:<?php echo $appearance['main']['color']; ?>}
	.theme_color{ color:<?php echo $appearance['main']['color']; ?>}

<?php endif; ?>

/* buttons */
<?php if ( $appearance['main']['button_color'] != '' ) : ?>
	button.button span{color:<?php echo $appearance['main']['button_color']; ?>}
<?php else: ?>
	button.button span{color:#000}
<?php endif; ?>
<?php if ( $appearance['main']['button_hover_color'] != '' ) : ?>
	.no-touch button.button:hover span {color:<?php echo $appearance['main']['button_hover_color']; ?>}
<?php else: ?>
	.no-touch button.button:hover span { color: #fff;}
<?php endif; ?>
<?php if ( $appearance['main']['button_bg_color'] != '' ) : ?>
	button.button > span:before, #toTop {background-color:<?php echo $appearance['main']['button_bg_color']; ?>}
<?php else: ?>
	button.button > span:before, #toTop {background-color:<?php echo $appearance['main']['color']; ?>}
<?php endif; ?>
<?php if ( $appearance['main']['button_bg_hover_color'] != '' ) : ?>
	button.button:hover > span:after, #toTop:hover {background-color:<?php echo $appearance['main']['button_bg_hover_color']; ?>}
<?php else: ?>
	button.button:hover > span:after, #toTop:hover {background-color:#000}
<?php endif; ?>
/* inverted buttons */
<?php if ( $appearance['main']['button_hover_color'] != '' ) : ?>
	button.inverted span {color:<?php echo $appearance['main']['button_hover_color']; ?>}
<?php else: ?>
	button.inverted span { color:#fff;}
<?php endif; ?>
<?php if ( $appearance['main']['button_color'] != '' ) : ?>
	.no-touch button.inverted:hover span{color:<?php echo $appearance['main']['button_color']; ?>}
<?php else: ?>
	.no-touch button.inverted:hover span { color:#000;}
<?php endif; ?>
<?php if ( $appearance['main']['button_bg_hover_color'] != '' ) : ?>
	.qty-container .qty-math,
	.data-table .btn-edit, .data-table .btn-remove, .block .btn-remove,
	button.inverted > span:before {background-color:<?php echo $appearance['main']['button_bg_hover_color']; ?>}
<?php else: ?>
	.qty-container .qty-math,
	.data-table .btn-edit, .data-table .btn-remove, .block .btn-remove,
	button.inverted > span:before { background-color: #000;}
<?php endif; ?>
<?php if ( $appearance['main']['button_bg_color'] != '' ) : ?>
	.qty-container .qty-math:hover,
	.data-table .btn-edit:hover, .data-table .btn-remove:hover, .block .btn-remove:hover,
	button.inverted:hover > span:after {background-color:<?php echo $appearance['main']['button_bg_color']; ?>}
<?php else: ?>
	.qty-container .qty-math:hover,
	.data-table .btn-edit:hover, .data-table .btn-remove:hover, .block .btn-remove:hover,
	button.inverted:hover > span:after {background-color:<?php echo $appearance['main']['color']; ?>}
<?php endif; ?>


/** cms banners **/
<?php if ( $appearance['main']['button_color'] != '' ) : ?>
	.cms-banner.cms-banner-big-link .link{color:<?php echo $appearance['main']['button_color']; ?>}
<?php else: ?>
	.cms-banner.cms-banner-big-link .link{color:#000}
<?php endif; ?>
<?php if ( $appearance['main']['button_hover_color'] != '' ) : ?>
	.no-touch .cms-banner.cms-banner-big-link .link:hover {color:<?php echo $appearance['main']['button_hover_color']; ?> !important}
<?php else: ?>
	.no-touch .cms-banner.cms-banner-big-link .link:hover { color: #fff !important;}
<?php endif; ?>
<?php if ( $appearance['main']['button_bg_color'] != '' ) : ?>
	.cms-banner.cms-banner-big-link .link {background-color:<?php echo $appearance['main']['button_bg_color']; ?>}
<?php else: ?>
	.cms-banner.cms-banner-big-link .link {background-color:<?php echo $appearance['main']['color']; ?>}
<?php endif; ?>
<?php if ( $appearance['main']['button_bg_hover_color'] != '' ) : ?>
	.cms-banner.cms-banner-big-link .link:hover {background-color:<?php echo $appearance['main']['button_bg_hover_color']; ?> !important}
<?php else: ?>
	.cms-banner.cms-banner-big-link .link:hover {background-color:#000 !important}
<?php endif; ?>


/** title **/
<?php if ($appearance['main']['enable_font'] == 1
	&& !empty($appearance['main']['title_font'])
	&& $appearance['main']['font'] != $appearance['main']['title_font'] ) : ?>
	.theme_title_font,
	.page-title h1,
	.block .block-title, .block-compare h3, .block_shipping .shipping > h2, .block_coupon .discount > h2, .block_totals #shopping-cart-totals-table tfoot strong,
	.std h1, .std h2, .std h3, .std h4,.std h5, .std h6,
	.std .h1, .std .h2, .std .h3, .std .h4,.std .h5, .std .h6,
	.product-view .product-category-title h3, .product-name h1,
	.dedicated-review-box ol.reviews-list li .review-title,
	.add-review h2, .add-review h4,
	.title-container h3
	{font-family:"<?php echo $appearance['main']['title_font']; ?>", Arial, sans-serif; }
<?php endif; ?>
<?php if ( !empty($appearance['main']['title_color']) ) : ?>
	.theme_title_color,
	.page-title h1,
	.block .block-title, .block-compare h3, .block_shipping .shipping > h2, .block_coupon .discount > h2, .block_totals #shopping-cart-totals-table tfoot strong,
	.std h1, .std h2, .std h3, .std h4,.std h5, .std h6,
	.std .h1, .std .h2, .std .h3, .std .h4,.std .h5, .std .h6,
	.product-view .product-category-title h3, .product-name h1,
	.dedicated-review-box ol.reviews-list li .review-title,
	.add-review h2, .add-review h4,
	.title-container h3
	{color:<?php echo $appearance['main']['title_color']; ?>}
<?php endif; ?>

/** price **/
<?php if ($appearance['main']['enable_font'] == 1
	&& !empty($appearance['main']['price_font'])
	&& $appearance['main']['font'] != $appearance['main']['price_font'] ) : ?>
	.price-box .price
	{font-family:"<?php echo $appearance['main']['price_font']; ?>", Arial, sans-serif; }
<?php endif; ?>
<?php if ( !empty($appearance['main']['price_color']) ) : ?>
	.price-box .price {color:<?php echo $appearance['main']['price_color']; ?>}
<?php endif; ?>
<?php if ( !empty($appearance['main']['price_old_color']) ) : ?>
	.price-box .old-price .price, .new-product .price-box .old-price .price, .sale-product .price-box .old-price .price
	{color:<?php echo $appearance['main']['price_old_color']; ?>}
<?php endif; ?>
<?php if ( !empty($appearance['main']['price_text_color']) ) : ?>
	.price-box, .minimal-price-link .label {color:<?php echo $appearance['main']['price_text_color']; ?>}
<?php endif; ?>
<?php if ( !empty($appearance['main']['new_price_color']) ) : ?>
	.new-product .price-box .price,
	.no-touch .products-grid li.new-product:hover .product-hover .animate-me .regular-price .price {color:<?php echo $appearance['main']['new_price_color']; ?>}
	.new-label {background-color:<?php echo $appearance['main']['new_price_color']; ?>}
<?php endif; ?>
<?php if ( !empty($appearance['main']['sale_price_color']) ) : ?>
	.sale-product .price-box .price,
	.products-grid li.item.hover .product-hover .animate-me .special-price .price {color:<?php echo $appearance['main']['sale_price_color']; ?>}
	.sale-label {background-color:<?php echo $appearance['main']['sale_price_color']; ?>}
<?php endif; ?>
<?php if ( !empty($appearance['main']['label_color']) ) : ?>
	.new-label, .sale-label {color:<?php echo $appearance['main']['label_color']; ?>}
<?php endif; ?>

/** header_options **/
<?php if ( $appearance['header']['header_bg'] != '' ) : ?>
.header-container, #nav, .header .form-search-over {background-color:<?php echo $appearance['header']['header_bg']; ?>}

<?php endif; ?>
<?php if ( $appearance['header']['logo_bg'] != '' ) : ?>
.logo-container {background-color:<?php echo $appearance['header']['logo_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['header']['top_bar_bg'] != '' ) : ?>
/*.top-bar,*/
.top-links-container, .top-links-container:before, .header .links:after {background-color:<?php echo $appearance['header']['top_bar_bg']; ?>}
.header-currency .header-switch-trigger:after, .header-language .header-switch-trigger:after {
	border-top-color:<?php echo $appearance['header']['top_bar_bg']; ?>;
}
<?php endif; ?>
<?php if ( $appearance['header']['top_bar_color'] != '' ) : ?>
.header-currency, .header-language, .header .top-links a {color:<?php echo $appearance['header']['top_bar_color']; ?>}
.header-currency .header-switch-trigger:before, .header-language .header-switch-trigger:before {
	border-top-color: <?php echo $appearance['header']['top_bar_color']; ?> ;
}
<?php endif; ?>
<?php if ( $appearance['header']['top_bar_hover_color'] != '' ) : ?>
.header .top-links a:hover, .header-cart .summary,
.header-currency:hover, .header-language:hover {color:<?php echo $appearance['header']['top_bar_hover_color']; ?>}
.header-currency:hover .header-switch-trigger:before, .header-language:hover .header-switch-trigger:before {
	border-top-color: <?php echo $appearance['header']['top_bar_hover_color']; ?> ;
}
<?php endif; ?>
<?php if ( $appearance['header']['top_bar_hover_bg_color'] != '' ) : ?>
.header .top-links a:hover, .header-cart .summary,
.header-currency:hover, .header-language:hover {background-color:<?php echo $appearance['header']['top_bar_hover_bg_color']; ?>}

@media only screen and (max-width: 767px) {
	.header-language, .header-currency {
		background-color:<?php echo $appearance['header']['top_bar_hover_bg_color']; ?>
	}
}

.header-currency:hover .header-switch-trigger:after, .header-language:hover .header-switch-trigger:after {
	border-top-color:<?php echo $appearance['header']['top_bar_hover_bg_color']; ?>;
	}
<?php endif; ?>
<?php if ( $appearance['header']['search_bg'] != '' ) : ?>
.header .form-search input {background-color:<?php echo $appearance['header']['search_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['header']['search_color'] != '' ) : ?>
.header .form-search input {color:<?php echo $appearance['header']['search_color']; ?>}
<?php endif; ?>

/** header_dropdowns **/
<?php if ( $appearance['header_dropdown']['top_dropdown_container'] != '' ) : ?>
.header-dropdown {background-color:<?php echo $appearance['header_dropdown']['top_dropdown_container']; ?>}
<?php endif; ?>
<?php if ( $appearance['header_dropdown']['top_dropdown_cart_bg_color'] != '' ) : ?>
.header-cart .cart-promotion, .header-cart .header-dropdown  ol li.item, .header-cart .header-dropdown .subtotal{background-color:<?php echo $appearance['header_dropdown']['top_dropdown_cart_bg_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['header_dropdown']['top_dropdown_buttons_bg'] != '' ) : ?>
.header-dropdown .btn-remove, .header-dropdown .btn-edit {background-color:<?php echo $appearance['header_dropdown']['top_dropdown_buttons_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['header_dropdown']['top_dropdown_color'] != '' ) : ?>
.header-dropdown, .header-dropdown ul li a, .header-cart .header-dropdown, .header-cart .header-dropdown ol li.item,
.header-cart .header-dropdown ol li.item a, .header-cart .header-dropdown .subtotal,
.header-cart .cart-promotion, .header-cart .cart-promotion a {
color : <?php echo $appearance['header_dropdown']['top_dropdown_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['header_dropdown']['top_dropdown_hover_color'] != '' ) : ?>
.header-dropdown ul li a:hover, .header-cart .header-dropdown ol li.item a:hover,
.header-cart .cart-promotion a:hover {color:<?php echo $appearance['header_dropdown']['top_dropdown_hover_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['header_dropdown']['top_dropdown_hover_bg_color'] != '' ) : ?>
.header-dropdown ul li a:hover, .header-cart .header-dropdown ol li.item a:hover,
.header-cart .cart-promotion a:hover {background-color:<?php echo $appearance['header_dropdown']['top_dropdown_hover_bg_color']; ?>}
<?php endif; ?>

/* navigation */
<?php if ( $appearance['navigation']['top_nav_bg'] != '' ) : ?>
.header-nav-wide:before {background-color:<?php echo $appearance['navigation']['top_nav_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['navigation']['top_nav_color'] != '' ) : ?>
#nav>li>a,
.nav-top-title a, .header-nav-txt.std, .header-nav-txt.std a {color:<?php echo $appearance['navigation']['top_nav_color']; ?>}
.nav-top-title:hover div.icon span,
.nav-top-title.active div.icon span {background-color:<?php echo $appearance['navigation']['top_nav_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['navigation']['top_nav_hover_color'] != '' ) : ?>
#nav>li>a:hover,
#nav>li.over>a,
#nav>li.active>a,
.nav-top-title:hover a, .header-nav-txt.std a {color:<?php echo $appearance['navigation']['top_nav_hover_color']; ?>}
.nav-top-title:hover div.icon span, .nav-top-title.active div.icon span {background-color:<?php echo $appearance['navigation']['top_nav_hover_color']; ?>}

<?php endif; ?>
<?php if ( $appearance['navigation']['top_nav_hover_bg_color'] != '' ) : ?>
#nav>li>a:hover,
#nav>li.over>a,
#nav>li.active>a,
#nav>li.parent>a:hover:before,
#nav>li.parent.over>a:before,
.nav-top-title:hover a,
.nav-top-title div.icon span, .header-nav-txt.std a{background-color:<?php echo $appearance['navigation']['top_nav_hover_bg_color']; ?>}
<?php endif; ?>
<?php if ($appearance['main']['enable_font'] == 1
	&& !empty($appearance['navigation']['top_nav_font'])
	&& $appearance['main']['font'] != $appearance['navigation']['top_nav_font'] ) : ?>
#nav > li > a, #nav ul.level0 li > a, .nav-top-title a,
#nav .std h1, #nav .std h2, #nav .std h3, #nav .std h4, #nav .std h5, #nav .std h6,
#nav .std .h1, #nav .std .h2, #nav .std .h3, #nav .std .h4, #nav .std .h5, #nav .std .h6,
#nav button.button span,
#nav li.custom-block ul li h4,
.nav-top-title
{font-family:"<?php echo $appearance['navigation']['top_nav_font']; ?>", Arial, sans-serif;}
<?php endif; ?>
<?php if ( $appearance['navigation']['top_nav_font_size'] != '' ) : ?>
#nav>li>a {font-size:<?php echo $appearance['navigation']['top_nav_font_size']; ?>px}
<?php endif; ?>
<?php if ( $appearance['navigation']['sub_nav_container'] != '' ) : ?>
#nav > li > div,
#nav ul.level0, #nav ul.level0 ul, #nav ul.level0 div,
#nav .title-container h3, #nav .title-container .slider-nav {background-color:<?php echo $appearance['navigation']['sub_nav_container']; ?>}
<?php endif; ?>
<?php if ( $appearance['navigation']['sub_nav_text_color'] != '' ) : ?>
#nav .title-container h3,
#nav .std h1, #nav .std h2, #nav .std h3, #nav .std h4, #nav .std h5, #nav .std h6,
#nav .std .h1, #nav .std .h2, #nav .std .h3, #nav .std .h4, #nav .std .h5, #nav .std .h6,
#nav .std {color:<?php echo $appearance['navigation']['sub_nav_text_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['navigation']['sub_nav_color'] != '' ) : ?>
#nav ul.level0 li a {color:<?php echo $appearance['navigation']['sub_nav_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['navigation']['sub_nav_hover_color'] != '' ) : ?>
#nav ul.level0 li a:hover, #nav ul.level0 li.active > a, #nav ul.level0 li.over > a {color:<?php echo $appearance['navigation']['sub_nav_hover_color']; ?>;
<?php if ($appearance['navigation']['sub_nav_hover_bg_color'] != '' ) : ?>
background-color:<?php echo $appearance['navigation']['sub_nav_hover_bg_color']; ?>
<?php endif; ?>
}
<?php endif; ?>
<?php if ( $appearance['navigation']['mm_border_color'] != '' ) : ?>
.megamenu-block .product-slider-container,
.olegnaxmegamenu #nav li.wide div div.megamenu-block .border-bottom,
.olegnaxmegamenu #nav li.wide div div.megamenu-block .border-left,
.olegnaxmegamenu #nav li.wide div div.megamenu-block .border-top {border-color:<?php echo $appearance['navigation']['mm_border_color']; ?>}
<?php endif; ?>

@media only screen and (max-width: 1023px) {
<?php if ( $appearance['navigation']['top_nav_color'] != '' ) : ?>
	#nav ul.level0 li a {color:<?php echo $appearance['navigation']['top_nav_color']; ?>}
<?php else: ?>
	#nav ul.level0 li a {color:#fff;}
<?php endif; ?>
<?php if ( $appearance['navigation']['top_nav_hover_color'] != '' ) : ?>
	#nav ul.level0 li a:hover, #nav ul.level0 li.active > a, #nav ul.level0 li.over > a {color:<?php echo $appearance['navigation']['top_nav_hover_color']; ?>}
<?php else: ?>
	#nav ul.level0 li a:hover, #nav ul.level0 li.active > a, #nav ul.level0 li.over > a {color:#000}
<?php endif; ?>
<?php if ( $appearance['navigation']['top_nav_hover_bg_color'] != '' ) : ?>
	#nav ul.level0 li a:hover, #nav ul.level0 li.active > a, #nav ul.level0 li.over > a {background-color:<?php echo $appearance['navigation']['top_nav_hover_bg_color']; ?>}
<?php elseif ( $appearance['main']['color'] != '' ) : ?>
	#nav ul.level0 li a:hover, #nav ul.level0 li.active > a, #nav ul.level0 li.over > a {background-color:<?php echo $appearance['main']['color']; ?>}
<?php endif; ?>
}

/** content_banners **/
<?php if ( $appearance['content_banners']['bg'] != '' ) : ?>
	.category-banner-container, .content-banner { background-color:<?php echo $appearance['content_banners']['bg']; ?>}
<?php endif; ?>
<?php if ($appearance['main']['enable_font'] == 1
	&& !empty($appearance['content_banners']['content_banner_font'])
	&& $appearance['main']['font'] != $appearance['content_banners']['content_banner_font'] ) : ?>
.content-banner .banner {font-family:"<?php echo $appearance['content_banners']['content_banner_font']; ?>",Arial, sans-serif;}
<?php endif; ?>
<?php if ( $appearance['content_banners']['content_banner_font_size'] != '' ) : ?>
.content-banner .banner {font-size:<?php echo $appearance['content_banners']['content_banner_font_size']; ?>px}
<?php endif; ?>
<?php if ( $appearance['content_banners']['title_bg'] != '' ) : ?>
	.category-banner-container .text-container .text { background-color:<?php echo $appearance['content_banners']['title_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['content_banners']['title_color'] != '' ) : ?>
	.category-banner-container .text-container .text { color:<?php echo $appearance['content_banners']['title_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['content_banners']['title_bg'] != '' ) : ?>
	.category-banner-container .text-container .text { background-color:<?php echo $appearance['content_banners']['title_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['content_banners']['title_color'] != '' ) : ?>
	.category-banner-container .text-container .text { color:<?php echo $appearance['content_banners']['title_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['content_banners']['link_bg'] != '' ) : ?>
	.category-banner-container .text-container .link { background-color:<?php echo $appearance['content_banners']['link_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['content_banners']['link_color'] != '' ) : ?>
	.category-banner-container .text-container .link { color:<?php echo $appearance['content_banners']['link_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['content_banners']['link_hover_bg'] != '' ) : ?>
	.no-touch .category-banner-container .link:hover { background-color:<?php echo $appearance['content_banners']['link_hover_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['content_banners']['link_hover_color'] != '' ) : ?>
	.no-touch .category-banner-container .link:hover { color:<?php echo $appearance['content_banners']['link_hover_color']; ?>}
<?php endif; ?>

/** Content area **/
<?php if ( $appearance['content']['content_bg'] != '' ) : ?>
	.main-container, .content-container, .brands-slider-container, .title-container h3, .title-container .slider-nav,
	.page-popup {background-color:<?php echo $appearance['content']['content_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['content']['content_border_bg'] != '' ) : ?>
	.product-slider-container,
	.brands-slider-container,
	.product-shop .social,
	.dedicated-review-box .average-rating,
	.dedicated-review-box ol.reviews-list,
	.add-review,
	.product-view .box-tags .form-add,
	.cart-table tfoot td,
	.top-line,
	#checkout-review-submit,
	.send-friend .form-list li.additional-row {border-top-color: <?php echo $appearance['content']['content_border_bg']; ?>;}

	.products-list li.item,
	.product-view .product-category-title {border-bottom-color: <?php echo $appearance['content']['content_border_bg']; ?>;}

	.border-top { border-top-color: <?php echo $appearance['content']['content_border_bg']; ?>;}
	.border-bottom { border-bottom-color: <?php echo $appearance['content']['content_border_bg']; ?>;}
	.border-left { border-left-color: <?php echo $appearance['content']['content_border_bg']; ?>;}
	.border-top { border-top-color: <?php echo $appearance['content']['content_border_bg']; ?>;}

	.fieldset {border-color: <?php echo $appearance['content']['content_border_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['content']['content_color'] != '' ) : ?>
	.content-container, .std {color:<?php echo $appearance['content']['content_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['content']['content_link_bg'] != '' ) : ?>
	.content-container a, .std a, .block-blog.block-blog-tags li a:hover {background-color:<?php echo $appearance['content']['content_link_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['content']['content_link_color'] != '' ) : ?>
	.content-container a, .std a, .block-blog.block-blog-tags li a:hover, .content-container table.rss-table a.link-rss, .content-container table.rss-table a.link-rss:hover {color:<?php echo $appearance['content']['content_link_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['content']['content_link_hover_bg'] != '' ) : ?>
	.opc .allow:hover .step-title .number,
	.opc .allow.active .step-title,
	.dashboard .box-reviews .number,
	.content-container a:hover, .std a:hover, .block-blog.block-blog-tags li a,
	.block-layered-nav li.active > a, .block-layered-nav li em:hover {background-color:<?php echo $appearance['content']['content_link_hover_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['content']['content_link_hover_color'] != '' ) : ?>
	.opc .allow:hover .step-title .number,
	.opc .allow.active .step-title,
	.dashboard .box-reviews .number,
	.content-container a:hover, .std a:hover, .block-blog.block-blog-tags li a,
	.block-layered-nav li.active > a, .block-layered-nav li em:hover {color:<?php echo $appearance['content']['content_link_hover_color']; ?>}
<?php endif; ?>
.product-shop .add-to-links a, .product-shop .add-to-links a:hover,
.products-grid .product-name a,
.data-table a.product-image, .data-table a.product-image:hover,
.banners-slider-container .banners li a,
.minimal-price-link,
.addthis_toolbox a,.addthis_toolbox a:hover, .cms-banner {background-color:transparent}

/** footer **/
<?php if ( $appearance['footer']['footer_bg'] != '' ) : ?>
.footer-container {background-color:<?php echo $appearance['footer']['footer_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['footer']['footer_border'] != '' ) : ?>
	.footer .facebook-block,
	.footer .info-content ul.block-tw-list li + li {border-top-color:<?php echo $appearance['footer']['footer_border']; ?>}
<?php endif; ?>
<?php if ($appearance['main']['enable_font'] == 1
	&& !empty($appearance['footer']['footer_title_font'])
	&& $appearance['main']['font'] != $appearance['footer']['footer_title_font'] ) : ?>

.footer .info-content h1,
.footer .info-content h2,
.footer .info-content h3,
.footer .info-content h4,
.footer .info-content h5,
.footer .info-content h6, .footer .newsletter .title, .footer .athlete_footer_connect .title, .athlete_footer_customer_service
{font-family:"<?php echo $appearance['footer']['footer_title_font']; ?>", Arial, sans-serif; letter-spacing:-0.1em;}
<?php endif; ?>
<?php if ( $appearance['footer']['footer_title_color'] != '' ) : ?>
.footer .info-content h1,
.footer .info-content h2,
.footer .info-content h3,
.footer .info-content h4,
.footer .info-content h5,
.footer .info-content h6, .footer .newsletter .title, .footer .athlete_footer_connect .title, .athlete_footer_customer_service
{color:<?php echo $appearance['footer']['footer_title_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['footer']['footer_text_color'] != '' ) : ?>
.footer, .footer .newsletter p, .footer .info-content a {color:<?php echo $appearance['footer']['footer_text_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['footer']['footer_link_color'] != '' ) : ?>
.footer a, .footer .info-content a {color:<?php echo $appearance['footer']['footer_link_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['footer']['footer_link_hover_color'] != '' ) : ?>
.footer a:hover, .footer .info-content a:hover, .footer .copyright-container a:hover {color:<?php echo $appearance['footer']['footer_link_hover_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['footer']['footer_link_hover_bg_color'] != '' ) : ?>
.footer a:hover, .footer .info-content a:hover, .copyright-container a:hover {background-color:<?php echo $appearance['footer']['footer_link_hover_bg_color']; ?>}
<?php endif; ?>

<?php if ( $appearance['footer']['footer_newsletter_bg'] != '' ) : ?>
.footer .newsletter {background-color:<?php echo $appearance['footer']['footer_newsletter_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['footer']['footer_button_color'] != '' ) : ?>
.footer button.button span {color:<?php echo $appearance['footer']['footer_button_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['footer']['footer_button_bg_color'] != '' ) : ?>
.footer button.button > span:before {background-color:<?php echo $appearance['footer']['footer_button_bg_color'];?>}
<?php endif; ?>
<?php if ( $appearance['footer']['footer_button_hover_color'] != '' ) : ?>
.no-touch .footer button.button:hover span {color:<?php echo $appearance['footer']['footer_button_hover_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['footer']['footer_button_bg_hover_color'] != '' ) : ?>
.no-touch .footer button.button:hover > span:before {background-color:<?php echo $appearance['footer']['footer_button_bg_hover_color']; ?>}
<?php endif; ?>

<?php if ( $appearance['footer']['copyright_bg'] != '' ) : ?>
body, .copyright-container {background-color:<?php echo $appearance['footer']['copyright_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['footer']['copyright_color'] != '' ) : ?>
.copyright-container, .copyright-container a {color:<?php echo $appearance['footer']['copyright_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['footer']['copyright_link_color'] != '' ) : ?>
.copyright-container a {color:<?php echo $appearance['footer']['copyright_link_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['footer']['copyright_hover_bg'] != '' ) : ?>
.copyright-container a:hover {background-color:<?php echo $appearance['footer']['copyright_hover_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['footer']['copyright_hover_color'] != '' ) : ?>
.copyright-container a:hover {color:<?php echo $appearance['footer']['copyright_hover_color']; ?>}
<?php endif; ?>



/* banners slider */
<?php if ( $appearance['banners_slider']['slide_bg'] != '' ) : ?>
    .banners-slider-container .banners li {background-color:<?php echo $appearance['banners_slider']['slide_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['banners_slider']['text_bg'] != '' ) : ?>
    .text-container .text {background-color:<?php echo $appearance['banners_slider']['text_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['banners_slider']['text_color'] != '' ) : ?>
    .text-container .text {color:<?php echo $appearance['banners_slider']['text_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['banners_slider']['text_hover_color'] != '' ) : ?>
    .no-touch .text-container .animate-me .text {color:<?php echo $appearance['banners_slider']['text_hover_color']; ?> !important}
<?php endif; ?>
<?php if ( $appearance['banners_slider']['text_bg_hover_color'] != '' ) : ?>
	.no-touch .text-container .text:after {background-color:<?php echo $appearance['banners_slider']['text_bg_hover_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['banners_slider']['link_bg'] != '' ) : ?>
    .text-container .link {background-color:<?php echo $appearance['banners_slider']['link_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['banners_slider']['link_color'] != '' ) : ?>
    .text-container .link {color:<?php echo $appearance['banners_slider']['link_color']; ?>}
<?php endif; ?>

<?php
$logo_width = $themeHelper->getCfg('header/logo_width', 'athlete', $_store->getId());
$logo_padding = $themeHelper->getCfg('header/logo_padding', 'athlete', $_store->getId());
if ( $logo_width < 0 || $logo_width > 320 ) {
	$logo_width = 260;
}
if ( ($logo_width + $logo_padding*2) > 320 ) {
	$logo_padding = floor( (320 - $logo_width)/2 );
}
?>
.logo-container-indent { padding: <?php echo $logo_padding ?>px }
@media only screen and (max-width: 767px) {
	.header .logo-container-indent { padding: <?php echo $logo_padding ?>px }
}
.logo-container {width:<?php echo $logo_width + $logo_padding*2 ?>px}
.header .logo img {max-width:<?php echo $logo_width ?>px}
.wide #nav ul.level0, .wide #nav > li > div,
.athlete #nav ul.level0, .athlete #nav > li > div,
.header-1 .olegnaxmegamenu #nav li.wide > div {margin-left:-<?php echo $logo_width + $logo_padding*2 ?>px}

@media only screen and (min-width: 768px) and (max-width: 1023px) {
	.header-nav-wide {left:<?php echo $logo_width + $logo_padding*2 ?>px;}
	
	/*
	.header .form-search-over, .header .search-visible .form-search-over {
		width:<?php echo (740 - ($logo_width + + $logo_padding*2 + 68)) ?>px;
	}
	*/
}
.header-fixed .header-2 .header-nav-wide {
	margin: -64px 90px 0;
}


/** Product page **/
.product-view .product-img-box {width: <?php echo $imgX; ?>px}
.product-view .product-img-box .product-image-zoom {width: <?php echo $imgX; ?>px; height: <?php echo $imgY; ?>px}
<?php if ( $imgX > 426 ) :?>
@media only screen and (max-width: 767px) {
	.product-view .product-img-box .product-image-zoom {width: 426px; height: <?php echo $imgHelper->calculateHeight(426); ?>px}
}
<?php endif; ?>
<?php if ( $imgX > 300 ) :?>
@media only screen and (max-width: 479px) {
	.product-view .product-img-box .product-image-zoom {width: 300px; height: <?php echo $imgHelper->calculateHeight(300); ?>px}
}
<?php endif; ?>

/** Login page **/
<?php if ( $appearance['login']['bg_color'] != '' ) : ?>
.customer-account-create .content-container,
.customer-account-forgotpassword .content-container,
.customer-account-resetpassword .content-container,
.customer-account-login .content-container { <?php echo 'background-color:' . $appearance['login']['bg_color'] .';' ; ?> }
<?php endif; ?>

/** Slideshow **/
<?php if ( !empty($appearance['slideshow']['bg_color']) ) : ?>
.slideshow-container {background-color:<?php echo $appearance['slideshow']['bg_color']; ?>}
<?php endif; ?>
<?php if ( !empty($appearance['slideshow']['timeline']) ) : ?>
.tp-bannertimer, .athlete-slideshow .slide .controls .progress {background-color:<?php echo $appearance['slideshow']['timeline']; ?>}
<?php endif; ?>
<?php if ( !empty($slideshow['revolutionslider']['startheight']) ) : ?>
	.fullwidthbanner-container, .fullwidthbanner-container .fullwidthbanner { max-height:<?php echo $slideshow['revolutionslider']['startheight']; ?>px !important;}
	.rs-banner{height:<?php echo $slideshow['revolutionslider']['startheight']; ?>px;}
	@media only screen and (min-width: 768px) and (max-width: 1023px) {
		.rs-banner, .rs-banner-container{ width:740px; max-height:<?php echo floor(768/960*$slideshow['revolutionslider']['startheight']); ?>px !important;}
	}
	@media only screen and (min-width: 480px) and (max-width: 767px) {
		.rs-banner, .rs-banner-container { width:426px; max-height:<?php echo floor(480/960*$slideshow['revolutionslider']['startheight']); ?>px !important; }
	}
	@media only screen and (min-width: 0px) and (max-width: 479px) {
		.rs-banner, .rs-banner-container { width:320px; max-height:<?php echo floor(320/960*$slideshow['revolutionslider']['startheight']); ?>px !important; }
	}
<?php endif; ?>
<?php if ( $appearance['main']['enable_font'] ) : ?>
	.fullwidthbanner-container .caption {font-family:"<?php echo $appearance['main']['font']; ?>"}
<?php endif; ?>
.tp-bullets.simplebullets.round .bullet:hover,
.tp-bullets.simplebullets.round .bullet.selected {background-color:<?php echo $appearance['main']['color']; ?>}
.tp-caption.athlete_white_bg_light, .tp-caption.athlete_white_bg_medium, .tp-caption.athlete_white_bg_bold {color:<?php echo $appearance['main']['color']; ?>}

<?php if ( $appearance['slideshow']['nav_bg'] != '' ) : ?>
	.tp-bullets.simplebullets.athlete .bullet, .tp-leftarrow.default, .tp-rightarrow.default,
	.athlete-slideshow .slide .controls .slide-control {background-color:<?php echo $appearance['slideshow']['nav_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['slideshow']['nav_hover_bg'] != '' ) : ?>
	.tp-bullets.simplebullets.athlete .bullet:hover,
	.tp-bullets.simplebullets.athlete .bullet.selected,
	.tp-leftarrow.default:hover, .tp-rightarrow.default:hover,
	.no-touch .athlete-slideshow .slide .controls .slide-control:hover {background-color:<?php echo $appearance['slideshow']['nav_hover_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['slideshow']['title_bg'] != '' ) : ?>
	.slide-title .text {background-color:<?php echo $appearance['slideshow']['title_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['slideshow']['title_color'] != '' ) : ?>
	.slide-title .text {color:<?php echo $appearance['slideshow']['title_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['slideshow']['link_bg'] != '' ) : ?>
	.slide-title .link {background-color:<?php echo $appearance['slideshow']['link_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['slideshow']['link_color'] != '' ) : ?>
	.slide-title .link {color:<?php echo $appearance['slideshow']['link_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['slideshow']['link_hover_bg'] != '' ) : ?>
	.slide-title .link:hover {background-color:<?php echo $appearance['slideshow']['link_hover_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['slideshow']['link_hover_color'] != '' ) : ?>
	.slide-title .link:hover {color:<?php echo $appearance['slideshow']['link_hover_color']; ?>}
<?php endif; ?>

/** Product listing **/
<?php if ($appearance['main']['enable_font'] == 1
	&& !empty($appearance['product_listing']['product_name_font'])
	&& $appearance['main']['font'] != $appearance['product_listing']['product_name_font'] ) : ?>
	.category-products .product-name {font-family:"<?php echo $appearance['product_listing']['product_name_font']; ?>", Arial, sans-serif; }
<?php endif; ?>
<?php if ( !empty($appearance['product_listing']['product_name_color']) ) : ?>
	.category-products .product-name a {color:<?php echo $appearance['product_listing']['product_name_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_listing']['rating_bg'] ) : ?>
	.my-account .data-table .ratings,
	.dashboard .box-reviews .ratings,
	.products-grid .ratings, .products-list .ratings .rating-box {background-color:<?php echo $appearance['product_listing']['rating_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_listing']['action_btn_bg'] ) : ?>
	.products-grid .actions .add-to-links li {background-color:<?php echo $appearance['product_listing']['action_btn_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_listing']['action_btn_hover_bg'] ) : ?>
	.products-grid .actions li button.button:hover, .products-grid .actions .add-to-links .link-wishlist:hover, .products-grid .actions .add-to-links .link-compare:hover {background-color:<?php echo $appearance['product_listing']['action_btn_hover_bg']; ?>}
<?php endif; ?>

<?php if ( $appearance['product_listing']['hover_bg'] ) : ?>
	.products-grid li.item.hover {background-color:<?php echo $appearance['product_listing']['hover_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_listing']['hover_title_bg'] ) : ?>
	.products-grid li.item.hover .product-name.animate-me:after,
	.products-grid li.item.hover .price-box.animate-me:after,
	.products-list .product-name a:hover {background-color:<?php echo $appearance['product_listing']['hover_title_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_listing']['hover_title_color'] ) : ?>
	.products-grid li.item.hover .product-hover .animate-me a,
	.products-grid li.item.hover .product-hover .animate-me p {color:<?php echo $appearance['product_listing']['product_name_color']; ?>}
	.products-grid li.item.hover .product-hover .animate-me a,
	.products-grid li.item.hover .product-hover .animate-me p,
	.products-list .product-name a:hover {color:<?php echo $appearance['product_listing']['hover_title_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_listing']['hover_price_color'] ) : ?>
	.products-grid li.item.hover .product-hover .animate-me .price,
	.products-grid li.item.hover .product-hover .animate-me .price-box,
	.products-grid li.item.hover .product-hover .animate-me .minimal-price-link .label {color:<?php echo $appearance['product_listing']['hover_price_color']; ?>}
<?php endif; ?>

<?php if ( $appearance['product_listing']['description_hover_color'] ) : ?>
	.no-touch .products-list li.item:hover .desc {color:<?php echo $appearance['product_listing']['description_hover_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_listing']['action_btn_color'] ) : ?>
	.products-list .add-to-links a {color:<?php echo $appearance['product_listing']['action_btn_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_listing']['action_btn_hover_color'] ) : ?>
	.products-list .add-to-links a:hover {color:<?php echo $appearance['product_listing']['action_btn_hover_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_listing']['action_btn_list_hover_bg'] ) : ?>
	.product-list .add-to-links a:hover .link_i {background-color:<?php echo $appearance['product_listing']['action_btn_list_hover_bg']; ?>}
<?php endif; ?>


/** Product details **/
<?php if ($appearance['main']['enable_font'] == 1
	&& !empty($appearance['product_info']['title_font'])
	&& $appearance['main']['font'] != $appearance['product_info']['title_font'] ) : ?>
	.product-view .page-title h1,
	.product-view .block .block-title,
	.product-view .std h2, .product-view .std h3, .product-view .std h4,
	.product-view .product-category-title h3, .product-view .product-name h1,
	.product-view .dedicated-review-box ol.reviews-list li .review-title,
	.product-view .add-review h2, .product-view .add-review h4,
	.product-view .title-container h3,
	.product-view .dedicated-review-box .average-rating strong
	{font-family:"<?php echo $appearance['product_info']['title_font']; ?>", Arial, sans-serif; }
<?php endif; ?>
<?php if ( !empty($appearance['product_info']['title_color']) ) : ?>
	.product-view .page-title h1,
	.product-view .block .block-title,
	.product-view .std h2, .product-view .std h3, .product-view .std h4,
	.product-view .product-category-title h3, .product-view .product-name h1,
	.product-view .dedicated-review-box ol.reviews-list li .review-title,
	.product-view .add-review h2, .product-view .add-review h4,
	.product-view .title-container h3,
	.product-view .dedicated-review-box .average-rating strong
	{color:<?php echo $appearance['product_info']['title_color']; ?>}
<?php endif; ?>
<?php if ( !empty($appearance['product_info']['text_color']) ) : ?>
	.product-view, .product-view .std {color:<?php echo $appearance['product_info']['text_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['link_bg'] != '' ) : ?>
	.product-view .std a {background-color:<?php echo $appearance['product_info']['link_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['link_color'] != '' ) : ?>
	.product-view .std a {color:<?php echo $appearance['product_info']['link_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['link_hover_bg'] != '' ) : ?>
	.product-view .std a:hover {background-color:<?php echo $appearance['product_info']['link_hover_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['link_hover_color'] != '' ) : ?>
	.product-view .std a:hover {color:<?php echo $appearance['product_info']['link_hover_color']; ?>}
<?php endif; ?>

<?php if ($appearance['main']['enable_font'] == 1
	&& !empty($appearance['product_info']['price_font'])
	&& $appearance['main']['font'] != $appearance['product_info']['price_font'] ) : ?>
	.product-shop .price-box .price, .product-options-bottom .price-box .price {font-family:"<?php echo $appearance['product_info']['price_font']; ?>", Arial, sans-serif; }
<?php endif; ?>
<?php if ( !empty($appearance['product_info']['price_color']) ) : ?>
	.product-shop .price-box .price, .product-options-bottom .price-box .price {color:<?php echo $appearance['product_info']['price_color']; ?>}
<?php endif; ?>
<?php if ( !empty($appearance['product_info']['price_old_color']) ) : ?>
	.product-shop .price-box .old-price .price,
	.product-shop.new-product .price-box .old-price .price,
	.product-shop.sale-product .price-box .old-price .price,
	.product-options-bottom .price-box .old-price .price,
	.product-options-bottom.new-product .price-box .old-price .price,
	.product-options-bottom.sale-product .price-box .old-price .price
	{color:<?php echo $appearance['product_info']['price_old_color']; ?>}
<?php endif; ?>
<?php if ( !empty($appearance['product_info']['price_text_color']) ) : ?>
	.product-shop .price-box, .product-shop .minimal-price-link .label,
	.product-options-bottom .price-box, .product-options-bottom .minimal-price-link .label {color:<?php echo $appearance['product_info']['price_text_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['button_color'] != '' ) : ?>
	.product-view button.button span{color:<?php echo $appearance['product_info']['button_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['button_hover_color'] != '' ) : ?>
	.no-touch .product-view button.button:hover span {color:<?php echo $appearance['product_info']['button_hover_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['button_bg_color'] != '' ) : ?>
	.product-view .qty-container .qty-math:hover,
	.product-view button.button > span:before {background-color:<?php echo $appearance['product_info']['button_bg_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['button_bg_hover_color'] != '' ) : ?>
	.product-view .qty-container .qty-math,
	.product-view button.button:hover > span:after {background-color:<?php echo $appearance['product_info']['button_bg_hover_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['action_btn_color'] ) : ?>
	.product-shop .add-to-links a {color:<?php echo $appearance['product_info']['action_btn_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['action_btn_hover_color'] ) : ?>
	.product-shop .add-to-links a:hover {color:<?php echo $appearance['product_info']['action_btn_hover_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['action_btn_list_hover_bg'] ) : ?>
	.product-shop .add-to-links a:hover .link_i {background-color:<?php echo $appearance['product_info']['action_btn_list_hover_bg']; ?>}
<?php endif; ?>
/* Product Tabs */
<?php if ( $appearance['product_info']['tab_color'] ) : ?>
	.product-tabs li a, .product-tabs-container h2.tab-heading a {color:<?php echo $appearance['product_info']['tab_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['tab_bg_color'] ) : ?>
	 .product-tabs li a, .product-tabs-container h2.tab-heading a {background-color:<?php echo $appearance['product_info']['tab_bg_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['tab_hover_color'] ) : ?>
	.product-tabs li.active a,
	.product-tabs li a:hover,
	.product-tabs-container h2.tab-heading a:hover,
	.product-tabs-container h2.active a,
	.product-tabs-container h2.active a:hover {color:<?php echo $appearance['product_info']['tab_hover_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['tab_bg_hover_color'] ) : ?>
	.product-tabs li.active a,
	.product-tabs li a:hover,
	.product-tabs-container h2.tab-heading a:hover,
	.product-tabs-container h2.active a,
	.product-tabs-container h2.active a:hover {background-color:<?php echo $appearance['product_info']['tab_bg_hover_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['tab_content_bg'] ) : ?>
	.product-tabs-content, .product-tabs-content .std {background-color:<?php echo $appearance['product_info']['tab_content_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['tab_content_color'] ) : ?>
	.product-tabs-content, .product-tabs-content .std {color:<?php echo $appearance['product_info']['tab_content_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['tab_content_link_bg'] != '' ) : ?>
	.product-tabs-content a, .product-tabs-content .std a, .product-tags li a {background-color:<?php echo $appearance['product_info']['tab_content_link_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['tab_content_link_color'] != '' ) : ?>
	.product-tabs-content a, .product-tabs-content .std a, .product-tags li a {color:<?php echo $appearance['product_info']['tab_content_link_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['tab_content_link_hover_bg'] != '' ) : ?>
	.product-tabs-content a:hover, .product-tabs-content .std a:hover, .product-tags li a:hover {background-color:<?php echo $appearance['product_info']['tab_content_link_hover_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['tab_content_link_hover_color'] != '' ) : ?>
	.product-tabs-content a:hover, .product-tabs-content .std a:hover, .product-tags li a:hover {color:<?php echo $appearance['product_info']['tab_content_link_hover_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['tab_content_th'] != '' ) : ?>
	#product-attribute-specs-table th {background-color:<?php echo $appearance['product_info']['tab_content_th']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['rating_bg'] ) : ?>
	.product-view .ratings .rating-box, .dedicated-review-box ol.reviews-list li .rating-box {background-color:<?php echo $appearance['product_info']['rating_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['rating_select_bg'] ) : ?>
	.add-review .data-table {background-color:<?php echo $appearance['product_info']['rating_select_bg']; ?>; border-color:<?php echo $appearance['product_info']['rating_select_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['rating_select_color'] ) : ?>
	.add-review .data-table th, .add-review .data-table td {color:<?php echo $appearance['product_info']['rating_select_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['rating_select_inactive'] ) : ?>
	.add-review .rating-radio {background-color:<?php echo $appearance['product_info']['rating_select_inactive']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['rating_select_active'] ) : ?>
	.add-review .rating-radio.active {background-color:<?php echo $appearance['product_info']['rating_select_active']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['rating_form_bg'] ) : ?>
	.add-review .form-list {background-color:<?php echo $appearance['product_info']['rating_form_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['rating_form_color'] ) : ?>
	.add-review .form-list label {color:<?php echo $appearance['product_info']['rating_form_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['cz_border'] ) : ?>
	.cloud-zoom-lens  {box-shadow: inset 0 0 0 3px <?php echo $appearance['product_info']['cz_border']; ?>}
	.cloud-zoom-big   {box-shadow: inset 0 0 0 9px <?php echo $appearance['product_info']['cz_border']; ?>}
<?php endif; ?>
<?php if ( $appearance['product_info']['cz_bg'] ) : ?>
	.cloud-zoom-lens  {background-color:rgba(<?php echo $colorHelper->hex2RGB($appearance['product_info']['cz_bg'], 1); ?>, <?php echo $appearance['product_info']['cz_bg_opacity']; ?> ); }
<?php endif; ?>

/** Sidebar **/
<?php if ( $appearance['sidebar']['block_border'] != '' ) : ?>
	.block {border-top-color:<?php echo $appearance['sidebar']['block_border']; ?>}
<?php endif; ?>
<?php if ( $appearance['sidebar']['block_items_border'] != '' ) : ?>
	.block-wishlist .block-content li.item + li.item {border-top-color:<?php echo $appearance['sidebar']['block_items_border']; ?>}
	.block-progress .block-title {border-bottom-color:<?php echo $appearance['sidebar']['block_items_border']; ?>}
<?php endif; ?>
<?php if ( $appearance['sidebar']['block_bg'] != '' ) : ?>
	.block {background-color:<?php echo $appearance['sidebar']['block_bg']; ?>}
<?php endif; ?>
<?php if ($appearance['main']['enable_font'] == 1
	&& !empty($appearance['sidebar']['block_title_font'])
	&& $appearance['main']['font'] != $appearance['sidebar']['block_title_font'] ) : ?>
	.block .block-title, .block-compare h3, .block_shipping .shipping > h2, .block_coupon .discount > h2
	{font-family:"<?php echo $appearance['sidebar']['block_title_font']; ?>", Arial, sans-serif;}
<?php endif; ?>
<?php if ( $appearance['sidebar']['block_title_font_size'] != '' ) : ?>
	.block .block-title, .block .block-title strong, .block-compare h3, .block_shipping .shipping > h2, .block_coupon .discount > h2 {font-size:<?php echo $appearance['sidebar']['block_title_font_size']; ?>px}
<?php endif; ?>
<?php if ( $appearance['sidebar']['block_title_color'] != '' ) : ?>
	.block .block-title, .block-compare h3, .block_shipping .shipping > h2, .block_coupon .discount > h2 {color:<?php echo $appearance['sidebar']['block_title_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['sidebar']['block_text_color'] != '' ) : ?>
	.block, .block label, .block-login label {color:<?php echo $appearance['sidebar']['block_text_color']; ?>}
	.blog-wrap span {color:<?php echo $appearance['sidebar']['block_text_color']; ?>; color:rgba(<?php echo $colorHelper->hex2RGB($appearance['sidebar']['block_text_color'], 1); ?>, 0.62); }
<?php endif; ?>
<?php if ( $appearance['sidebar']['block_link_color'] != '' ) : ?>
	.block a, .block-layered-nav li a, .block-layered-nav li em, .block-viewed li a, .block-account li a, .block-tags li a {color:<?php echo $appearance['sidebar']['block_link_color']; ?>}
	.block-viewed li a:hover, .block-wishlist p.product-name a:hover, .content-container .blog-wrap a:hover { background-color: transparent; color:<?php echo $appearance['sidebar']['block_link_color']; ?>; color:rgba(<?php echo $colorHelper->hex2RGB($appearance['sidebar']['block_link_color'], 1); ?>, 0.7 ); }
<?php endif; ?>
<?php if ( $appearance['sidebar']['block_link_hover_color'] != '' ) : ?>
	.block a:hover, .block-layered-nav li a:hover, .block-layered-nav li em:hover, .block-layered-nav li.active > a, .block-account li a:hover, .block-tags li a:hover {color:<?php echo $appearance['sidebar']['block_link_hover_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['sidebar']['block_link_hover_bg'] != '' ) : ?>
	.block a:hover, .block-layered-nav li a:hover, .block-layered-nav li em:hover, .block-layered-nav li.active > a, .block-account li a:hover, .block-tags li a:hover {background-color:<?php echo $appearance['sidebar']['block_link_hover_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['sidebar']['button_color'] != '' ) : ?>
	.block .actions a, .block button.button span{color:<?php echo $appearance['sidebar']['button_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['sidebar']['button_hover_color'] != '' ) : ?>
	.block .actions a:hover, .no-touch .block button.button:hover span {color:<?php echo $appearance['sidebar']['button_hover_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['sidebar']['button_bg_color'] != '' ) : ?>
	.block .actions a, .block button.button > span:before {background-color:<?php echo $appearance['sidebar']['button_bg_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['sidebar']['button_bg_hover_color'] != '' ) : ?>
	.block .actions a:hover, .block button.button:hover > span:after {background-color:<?php echo $appearance['sidebar']['button_bg_hover_color']; ?>}
<?php endif; ?>
	/* inverted buttons */
<?php if ( $appearance['sidebar']['button_hover_color'] != '' ) : ?>
	.block button.inverted span {color:<?php echo $appearance['sidebar']['button_hover_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['sidebar']['button_color'] != '' ) : ?>
	.no-touch .block button.inverted:hover span{color:<?php echo $appearance['sidebar']['button_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['sidebar']['button_bg_hover_color'] != '' ) : ?>
	.block button.inverted > span:before {background-color:<?php echo $appearance['sidebar']['button_bg_hover_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['sidebar']['button_bg_color'] != '' ) : ?>
	.block button.inverted:hover > span:after {background-color:<?php echo $appearance['sidebar']['button_bg_color']; ?>}
<?php endif; ?>
/** poll **/
<?php if ( $appearance['sidebar']['block_poll_q_bg'] != '' ) : ?>
	.block-poll .block-subtitle {background-color:<?php echo $appearance['sidebar']['block_poll_q_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['sidebar']['block_poll_q_color'] != '' ) : ?>
	.block-poll .block-subtitle {color:<?php echo $appearance['sidebar']['block_poll_q_color']; ?>}
<?php endif; ?>

/** Global Messages  **/
<?php if ( $appearance['messages']['success_bg'] != '' ) : ?>
	.success-msg { background-color:<?php echo $appearance['messages']['success_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['messages']['success_color'] != '' ) : ?>
	.success, .main ul.messages > li.success-msg {color:<?php echo $appearance['messages']['success_color']; ?>}
<?php endif; ?>
	
<?php if ( $appearance['messages']['error_bg'] != '' ) : ?>
	.error-msg { background-color:<?php echo $appearance['messages']['error_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['messages']['error_color'] != '' ) : ?>
	.error, .main ul.messages > li.error-msg {color:<?php echo $appearance['messages']['error_color']; ?>}
<?php endif; ?>
	
<?php if ( $appearance['messages']['notice_bg'] != '' ) : ?>
	.notice-msg, .note-msg { background-color:<?php echo $appearance['messages']['notice_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['messages']['notice_color'] != '' ) : ?>
	.notice, .main ul.messages > li.notice-msg, .main ul.messages > li.note-msg {color:<?php echo $appearance['messages']['notice_color']; ?>}
<?php endif; ?>

/** Pager  **/
<?php if ( $appearance['pager']['pager_bg'] != '' ) : ?>
	.sorter, .pager { background-color:<?php echo $appearance['pager']['pager_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['pager']['pager_color'] != '' ) : ?>
	.sorter, .pager { color:<?php echo $appearance['pager']['pager_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['pager']['pager_link_bg'] != '' ) : ?>
	.pager .pages li a { color:<?php echo $appearance['pager']['pager_link_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['pager']['pager_link_color'] != '' ) : ?>
	.pager .pages li a { color:<?php echo $appearance['pager']['pager_link_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['pager']['pager_link_hover_bg'] != '' ) : ?>
	.pager .pages li a:hover, .pager .pages li.current { background-color:<?php echo $appearance['pager']['pager_link_hover_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['pager']['pager_link_hover_color'] != '' ) : ?>
	.pager .pages li a:hover, .pager .pages li.current { color:<?php echo $appearance['pager']['pager_link_hover_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['pager']['pager_dropdown_bg'] != '' ) : ?>
	.pager .limiter,
	.sorter .sort-by-wrap, .sorter .view-mode, .sorter .limiter,
	.pager .pages li a.previous, .pager .pages li a.next,
	.sorter a.sort-by-arrow, .view-mode .grid, .view-mode .list { background-color:<?php echo $appearance['pager']['pager_dropdown_bg']; ?>}
	.toolbar-dropdown { border-top-color:<?php echo $appearance['pager']['pager_dropdown_bg']; ?>; background-color:<?php echo $appearance['pager']['pager_dropdown_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['pager']['pager_dropdown_color'] != '' ) : ?>
	.pager .limiter,
	.sorter .sort-by-wrap, .sorter .view-mode, .sorter .limiter { color:<?php echo $appearance['pager']['pager_dropdown_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['pager']['pager_dropdown_link_color'] != '' ) : ?>
	.sorter .current, .toolbar-dropdown ul li a { color:<?php echo $appearance['pager']['pager_dropdown_link_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['pager']['pager_dropdown_link_hover_color'] != '' ) : ?>
	.over .toolbar-title,
	.toolbar-dropdown ul li a:hover, .toolbar-dropdown ul li.selected a,
	.view-mode a.grid:hover, .view-mode strong.grid, .view-mode a.list:hover, .view-mode strong.list,
	.pager .pages li a.previous :hover, .pager .pages li a.next:hover { color:<?php echo $appearance['pager']['pager_dropdown_link_hover_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['pager']['pager_dropdown_link_hover_bg'] != '' ) : ?>
	.over .toolbar-title,
	.sorter a.sort-by-arrow:hover,
	.toolbar-dropdown ul li a:hover, .toolbar-dropdown ul li.selected a,
	.view-mode a.grid:hover, .view-mode strong.grid, .view-mode a.list:hover, .view-mode strong.list,
	.pager .pages li a.previous :hover, .pager .pages li a.next:hover { background-color:<?php echo $appearance['pager']['pager_dropdown_link_hover_bg']; ?> }
<?php endif; ?>

/** Arrows  **/

/* banner slider */
<?php if ( $appearance['arrows']['banners_slider_bg'] != '' ) : ?>
	.banners-slider-container .nav a { background-color:<?php echo $appearance['arrows']['banners_slider_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['arrows']['banners_slider_hover_bg'] != '' ) : ?>
	.no-touch .banners-slider-container .nav a:hover { background-color:<?php echo $appearance['arrows']['banners_slider_hover_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['arrows']['banners_slider_disabled_bg'] != '' ) : ?>
	.banners-slider-container .nav a.disabled, .no-touch .banners-slider-container .nav a.disabled:hover { background-color:<?php echo $appearance['arrows']['banners_slider_disabled_bg']; ?>}
<?php endif; ?>

/* brands slider */
<?php if ( $appearance['arrows']['brands_slider_bg'] != '' ) : ?>
	.brands-slider-container .title-container .slider-nav a { background-color:<?php echo $appearance['arrows']['brands_slider_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['arrows']['brands_slider_hover_bg'] != '' ) : ?>
	.no-touch .brands-slider-container .title-container .slider-nav a:hover { background-color:<?php echo $appearance['arrows']['brands_slider_hover_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['arrows']['brands_slider_disabled_bg'] != '' ) : ?>
	.brands-slider-container .title-container .slider-nav a.disabled, .no-touch .brands-slider-container .title-container .slider-nav a.disabled:hover { background-color:transparent;}
<?php endif; ?>

/* Prevnext */
<?php if ( $appearance['arrows']['pn_slider_bg'] != '' ) : ?>
	.prev-next a, .prev-next a.icon-white { background-color:<?php echo $appearance['arrows']['pn_slider_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['arrows']['pn_slider_hover_bg'] != '' ) : ?>
	.no-touch .prev-next a:hover, .no-touch .prev-next a.icon-white:hover { background-color:<?php echo $appearance['arrows']['pn_slider_hover_bg']; ?>}
<?php endif; ?>

/* product slider */
<?php if ( $appearance['arrows']['products_slider_bg'] != '' ) : ?>
	.title-container .slider-nav a, .product-view .product-img-box .more-views-nav a { background-color:<?php echo $appearance['arrows']['products_slider_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['arrows']['products_slider_hover_bg'] != '' ) : ?>
	.no-touch .title-container .slider-nav a:hover, .product-view .product-img-box .more-views-nav a:hover { background-color:<?php echo $appearance['arrows']['products_slider_hover_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['arrows']['products_slider_disabled_bg'] != '' ) : ?>
	.title-container .slider-nav a.disabled, .no-touch .title-container .slider-nav a.disabled:hover,
	.product-view .product-img-box .more-views-nav a.disabled, .product-view .product-img-box .more-views-nav a.disabled:hover{ background-color:<?php echo $appearance['arrows']['products_slider_disabled_bg']; ?>}
<?php endif; ?>

/* product slider - megamenu */
<?php if ( $appearance['arrows']['mm_products_slider_bg'] != '' ) : ?>
	.megamenu-block .product-slider-container .title-container .slider-nav a { background-color:<?php echo $appearance['arrows']['mm_products_slider_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['arrows']['mm_products_slider_hover_bg'] != '' ) : ?>
	.no-touch .megamenu-block .product-slider-container .title-container .slider-nav a:hover { background-color:<?php echo $appearance['arrows']['mm_products_slider_hover_bg']; ?>}
<?php endif; ?>

/* banner slider */
<?php
$bannersliderBlock = new Olegnax_Athlete_Block_Bannerslider();
$groups = Mage::getModel('athlete/bannerslider_group')->getCollection()->addFieldToSelect('*');
foreach ($groups as $_group) {
?>
	/* <?php echo $bannersliderBlock->getSliderId($_group->getGroupName())?> */
	<?php echo '#'.$bannersliderBlock->getSliderId($_group->getGroupName())?> .banners {height: 0px; }
	<?php echo '#'.$bannersliderBlock->getSliderId($_group->getGroupName())?> .banners li a { width: <?php echo $_group->getSlideWidth()?>px; height: <?php echo $_group->getSlideHeight()?>px; }
<?php } ?>


/* fancybox */

<?php if ( $appearance['main']['button_bg_hover_color'] != '' ) : ?>
	#fancybox-close {background-color:<?php echo $appearance['main']['button_bg_hover_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['main']['button_bg_color'] != '' ) : ?>
	#fancybox-close:hover {background-color:<?php echo $appearance['main']['button_bg_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['main']['inverted_button_icons'] == 'white' ) : ?>
	#fancybox-close { background-position: 5px 4px; }
	#fancybox-close:hover { background-position: 5px -17px }
<?php else: ?>
	#fancybox-close { background-position: 5px -17px; }
	#fancybox-close:hover { background-position: 5px 4px }
<?php endif; ?>

<?php if ( $appearance['content']['content_bg'] != '' ) : ?>
	#fancybox-outer {background-color:<?php echo $appearance['content']['content_bg']; ?>}
	##fancybox-content {border-color:<?php echo $appearance['content']['content_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['content']['content_color'] != '' ) : ?>
	.ajax-message {color:<?php echo $appearance['content']['content_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['content']['content_link_bg'] != '' ) : ?>
	.ajax-message a {background-color:<?php echo $appearance['content']['content_link_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['content']['content_link_color'] != '' ) : ?>
	.ajax-message a {color:<?php echo $appearance['content']['content_link_color']; ?>}
<?php endif; ?>
<?php if ( $appearance['content']['content_link_hover_bg'] != '' ) : ?>
	.ajax-message a:hover {background-color:<?php echo $appearance['content']['content_link_hover_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['content']['content_link_hover_color'] != '' ) : ?>
	.ajax-message a:hover {color:<?php echo $appearance['content']['content_link_hover_color']; ?>}
<?php endif; ?>



/* blog */
<?php if ( $appearance['main']['button_hover_color'] != '' ) : ?>
	.blog-date .inner {color:<?php echo $appearance['main']['button_hover_color']; ?>}
<?php else: ?>
	.blog-date .inner { color:#fff;}
<?php endif; ?>
<?php if ( $appearance['main']['button_color'] != '' ) : ?>
	.blog-date .hover {color:<?php echo $appearance['main']['button_color']; ?>}
<?php else: ?>
	.blog-date .hover { color:#000;}
<?php endif; ?>
<?php if ( $appearance['main']['button_bg_hover_color'] != '' ) : ?>
	.blog-date .inner {background-color:<?php echo $appearance['main']['button_bg_hover_color']; ?>}
<?php else: ?>
	.blog-date .inner { background-color: #000;}
<?php endif; ?>
<?php if ( $appearance['main']['button_bg_color'] != '' ) : ?>
	.blog-date .hover {background-color:<?php echo $appearance['main']['button_bg_color']; ?>}
<?php else: ?>
	.blog-date .hover {background-color:<?php echo $appearance['main']['color']; ?>}
<?php endif; ?>


<?php if ( $appearance['content']['content_link_hover_bg'] != '' ) : ?>
	.postWrapper:hover .postTitle h2 a {background-color:<?php echo $appearance['content']['content_link_hover_bg']; ?>}
<?php endif; ?>
<?php if ( $appearance['content']['content_link_hover_color'] != '' ) : ?>
	.postWrapper:hover .postTitle h2 a {color:<?php echo $appearance['content']['content_link_hover_color']; ?>}
<?php endif; ?>


<?php if ( $appearance['main']['color'] != '' ) : ?>
	.block-blog.block-blog-tags li a:hover, .blog-img-wrap a:after {background-color:<?php echo $appearance['main']['color']; ?>}
	.commentWrapper {border-color:<?php echo $appearance['main']['color']; ?>}
<?php endif; ?>





/*****************************************************************/
/***************** theme layout & max width **********************/
<?php
$responsive = $themeHelper->getCfg('layout/responsive', 'athlete', $_store->getId());
$fluid = $themeHelper->getCfg('layout/fluid', 'athlete',  $_store->getId());
$maxWidth = $layoutHelper->getMaxWidth($_store->getId());
$customWidth = $layoutHelper->getCustomWidth($_store->getId());

$breakpoints = $layoutHelper->getBreakpoints();
$bpContentWidth = $layoutHelper->getBreakpointsContentWidth();
$maxBreakpoint = $layoutHelper->getMaxBreakpoint( $maxWidth );
?>

<?php if ( $responsive ) : ?>

<?php if ( $fluid ) : ?>
	<?php if ( $customWidth ) : ?>
		.grid-fluid .row { max-width: <?php echo $customWidth; ?>px; }
	<?php else: ?>
		.grid-fluid .row { max-width: <?php echo $bpContentWidth[$maxWidth]; ?>px; }
	<?php endif; ?>
<?php endif; ?>

<?php if ( $maxBreakpoint >= 1680 ) : ?>
/* Desktop width - 1680px */
@media only screen and (min-width: 1680px) {
<?php if ( !$fluid ) : ?>
	<?php if ( $customWidth && $maxBreakpoint >= 1680 ) : ?>
		.row { max-width: <?php echo $customWidth; ?>px; }
	<?php else: ?>
		.row { max-width: <?php echo $bpContentWidth['1680']; ?>px; }
	<?php endif; ?>
<?php endif; ?>

/* default 2 columns */
.col2-layout .sidebar	{ width: 16.11%;}
.col2-layout .col-main	{ width: 79.88%;}

/* default 3 columns */
.col3-layout .grid_14 	{ width: 79.88%;}
.col3-layout .col-main 	{ width: 77.34%;}
.col3-layout .col-left 	{ width: 20.18%;}
.col3-layout .col-right { width: 16.11%;}

/* product item */
.product-columns-2 ul.products-grid li.item { width: 20%;}
.product-columns-3 ul.products-grid li.item { width: 16.6666%;}
.product-columns-4 ul.products-grid li.item { width: 14.2857%;}
.product-columns-5 ul.products-grid li.item { width: 12.5%;}
.product-columns-6 ul.products-grid li.item { width: 12.5%;}
.product-columns-7 ul.products-grid li.item { width: 12.5%;}
}
<?php endif; ?>

<?php if ( $maxBreakpoint >= 1440 ) : ?>
/* Desktop width - 1440px */
@media only screen and (min-width: 1440px) <?php if ( $maxBreakpoint > 1440 ) : ?>and (max-width: 1679px)<?php endif; ?> {
<?php if ( !$fluid ) : ?>
	<?php if ( !$fluid ) : ?>
		<?php if ( $customWidth && $maxBreakpoint == 1440 ) : ?>
			.row { max-width: <?php echo $customWidth; ?>px; }
		<?php else: ?>
			.row { max-width: <?php echo $bpContentWidth['1440']; ?>px; }
		<?php endif; ?>
	<?php endif; ?>
<?php endif; ?>

/* default 2 columns */
.col2-layout .sidebar  { width: 17.75%;}
.col2-layout .col-main { width: 78.24%;}

/* default 3 columns */
.col3-layout .grid_14 	{ width: 78.24%;}
.col3-layout .col-main  { width: 74.90%;}
.col3-layout .col-left  { width: 22.68%;}
.col3-layout .col-right { width: 17.75%;}

/* product item */
.product-columns-2 ul.products-grid li.item { width: 25%;}
.product-columns-3 ul.products-grid li.item { width: 20%;}
.product-columns-4 ul.products-grid li.item { width: 16.6666%;}
.product-columns-5 ul.products-grid li.item { width: 14.2857%;}
.product-columns-6 ul.products-grid li.item { width: 12.5%;}
.product-columns-7 ul.products-grid li.item { width: 12.5%;}
}
<?php endif; ?>


<?php if ( $maxBreakpoint >= 1360 ) : ?>
/* Desktop width - 1360px */
@media only screen and (min-width: 1360px) <?php if ( $maxBreakpoint > 1360 ) : ?>and (max-width: 1439px)<?php endif; ?> {
<?php if ( !$fluid ) : ?>
	<?php if ( !$fluid ) : ?>
		<?php if ( $customWidth && $maxBreakpoint == 1360 ) : ?>
			.row { max-width: <?php echo $customWidth; ?>px; }
		<?php else: ?>
			.row { max-width: <?php echo $bpContentWidth['1360']; ?>px; }
		<?php endif; ?>
	<?php endif; ?>
<?php endif; ?>

/* default 2 columns */
.col2-layout .sidebar  { width: 18.84%;}
.col2-layout .col-main { width: 77.15%;}

/* default 3 columns */
.col3-layout .grid_14 	{ width: 77.15%;}
.col3-layout .col-main  { width: 72.98%;}
.col3-layout .col-left  { width: 24.42%;}
.col3-layout .col-right { width: 18.84%;}

/* product item */
.product-columns-2 ul.products-grid li.item { width: 33.3333%;}
.product-columns-3 ul.products-grid li.item { width: 25%;}
.product-columns-4 ul.products-grid li.item { width: 20%;}
.product-columns-5 ul.products-grid li.item { width: 16.6666%;}
.product-columns-6 ul.products-grid li.item { width: 14.2857%;}
.product-columns-7 ul.products-grid li.item { width: 12.5%;}
}
<?php endif; ?>

<?php if ( $maxBreakpoint >= 1280 ) : ?>
/* Desktop width - 1280px */
@media only screen and (min-width: 1280px) <?php if ( $maxBreakpoint > 1280 ) : ?>and (max-width: 1359px)<?php endif; ?> {
<?php if ( !$fluid ) : ?>
	<?php if ( !$fluid ) : ?>
		<?php if ( $customWidth && $maxBreakpoint == 1280 ) : ?>
			.row { max-width: <?php echo $customWidth; ?>px; }
		<?php else: ?>
			.row { max-width: <?php echo $bpContentWidth['1280']; ?>px; }
		<?php endif; ?>
	<?php endif; ?>
<?php endif; ?>

/* default 2 columns */
.col2-layout .sidebar  { width: 20.41%;}
.col2-layout .col-main { width: 75.58%;}

/* default 3 columns */
.col3-layout .grid_14 	{ width: 75.58%;}
.col3-layout .col-main  { width: 70.34%;}
.col3-layout .col-left  { width: 27.01%;}
.col3-layout .col-right { width: 20.41%;}

/* product item */
.product-columns-2 ul.products-grid li.item { width: 33.3333%;}
.product-columns-3 ul.products-grid li.item { width: 25%;}
.product-columns-4 ul.products-grid li.item { width: 20%;}
.product-columns-5 ul.products-grid li.item { width: 16.6666%;}
.product-columns-6 ul.products-grid li.item { width: 14.2857%;}
.product-columns-7 ul.products-grid li.item { width: 12.5%;}
}
<?php endif; ?>

<?php else: // if ( $responsive ) : ?>

<?php
$_width = $bpContentWidth[$maxWidth];
if ($customWidth) $_width = $customWidth;
?>
body { min-width: <?php echo $_width ?>px; }
.row { width: <?php echo $_width ?>px; max-width: <?php echo $_width ?>px; }
body { width: <?php echo $_width ?>px; }

<?php endif; // if ( $responsive ) : ?>