<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>
<div class="blog-title">
	<h1><?php echo Mage::getStoreConfig('blog/blog/title'); ?></h1>
</div>
<?php //echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
<?php foreach ($posts as $post): ?>
    <div class="postWrapper">
	    <?php if ($post->getImage()) : list($width, $height, $type, $attr) = getimagesize(Mage::getBaseUrl('media'). $post->getImage()); ?>
		<div class="blog-img-wrap">
			<a class="blog-img-link" href="<?php echo $post->getAddress(); ?>">
				<img <?php echo $attr; ?> class="blog-img" src="<?php echo Mage::getBaseUrl('media') . $post->getImage(); ?>" <?php echo ($post->getImageRetina() ? 'data-srcX2="'.Mage::getBaseUrl('media') . $post->getImageRetina().'"' : '' ); ?>>
			</a>
		</div>
	    <?php endif; ?>
		<h3 class="blog-date">
			<div class="inner">
			<?php
			$t = strtotime($post->getCreatedTime());
			echo '<span class="day">'.date('d', $t).'</span>'.date('M', $t);
			?>
			</div>
			<div class="hover">
				<?php echo '<span class="day">'.date('d', $t).'</span>'.date('M', $t); ?>
			</div>
		</h3>
		<div class="postContentWrapper">	
			<div class="postTitle">				
				<h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
				<div class="postDetails">
					<?php if ($this->getCommentsEnabled()): ?>
						<a href="<?php echo $post->getAddress(); ?>#commentBox" ><?php echo $post->getCommentCount(); ?> Comments</a><span class="separator">|</span>
					<?php endif; ?>
					<?php $postCats = $post->getCats(); ?>
					<?php if (!empty($postCats)): ?>
						<?php echo Mage::helper('blog')->__('Posted in'); ?>
						<?php foreach ($postCats as $data): ?>
							<a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a>
						<?php endforeach; ?>
					<?php else: ?>
						<?php echo Mage::helper('blog')->__('Posted'); ?>
					<?php endif; ?><?php echo $this->__("By"); ?> <?php echo $post->getUser(); ?>
				</div>
			</div>
			<div class="postContent std"><?php echo $post->getPostContent(); ?></div>
			<?php //echo $this->getBookmarkHtml($post) ?>
			<!--<div class="tags"><?php //echo $this->getTagsHtml($post) ?></div>-->
		 </div>		
    </div>
<?php endforeach; ?>
<?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>