<?php echo $this->getChildHtml('athlete_brands'); ?>
<?php echo $this->getChildHtml('bottomContainer'); ?>
<div class="footer-container">
	<div class="footer row clearfix">
		<div class="grid_18">
			<div class="footer-info clearfix">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId(Mage::helper('athlete')->getCfg('footer/cms_block'))->toHtml(); ?>
			</div>
			<div class="facebook-block">
				<!-- <div class="fb-like" data-share="false" data-send="false" data-layout="standard" data-width="270" data-height="35" data-show-faces="false" data-font="arial" data-colorscheme="<?php echo $this->helper('athlete')->getCfg('social/facebook_scheme') ?>" data-action="like"></div>
				<div class="athlete_footer_customer_service">
					<?php echo $this->getChildHtml('athlete_footer_customer_service');?>
				</div> -->
				<div class="newletter_footer">
					<?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe_footer.phtml')->toHtml(); ?>
				</div>
				<div class="social_footer"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('athlete_footer_connect')->toHtml(); ?></div> 
			</div>
		</div>
	</div>
</div>
<div class="copyright-container">
	<div class="row clearfix">
		<div class="grid_18">
			<address><?php echo $this->getCopyright() ?></address>
			<!-- <div class="cc-icons"><?php echo $this->getChildHtml('athlete_cc_icons');?></div> -->
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_fmenu')->toHtml(); ?>
		</div>
	</div>
</div>
<div id="fb-root"></div>
<script>(function(d, s, id) {
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id))
			return;
		js = d.createElement(s);
		js.id = id;
		js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=195555774072";
		fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>