<?php
$deal_id = Mage::getSingleton('core/session')->getData('dailydeal_report_id');
$deal = Mage::getModel('dailydeal/deal')->load($deal_id);
?>

<div class="content-header">
  <table cellspacing="0">
    <tbody><tr>
      <td style="width:50%;"><h3 class="icon-head head-adminhtml-dailydeal">Deal Report: <?php echo $deal->getTitle(); ?></h3></td>
    </tr>
    </tbody></table>
</div>

<?php
$days = (int) (strtotime($deal->getEndTime()) - strtotime($deal->getStartTime()))/(3600*24);
$product_id = $deal->getProductId();
// Zend_Debug::dump($days);

// $graph_type = 'day';
$x_unit = 1*3600*24; //day

$fromDate = strtotime($deal->getStartTime());
$toDate = strtotime($deal->getEndTime());

$graph_before = array();


$now = Mage::getModel('core/date')->gmtTimestamp();
$graph = array();
$max_item = 0;
$total = 0;
for ($i = -7; $fromDate + $i*$x_unit <= min($toDate + 7*$x_unit,$now); $i++) {
  $start = $fromDate + $x_unit*$i;
  $collection = Mage::getModel('sales/order_item')->getCollection();
  $collection->addAttributeToFilter('created_at', array('from'=>date('Y-m-d 00:00:00', $start), 'to'=>date('Y-m-d 23:59:59', $start)));
  $collection->addAttributeToFilter('product_id', array('eq'=>$product_id));
  $number_item = 0;
  foreach ($collection as $item) {
    $number_item += $item->getQtyOrdered();
  }
  if ($number_item > $max_item) $max_item = $number_item;
  $day_in_deal = (($start > $fromDate)&&($start < $toDate)) ? 1 : 0;
  $graph[] = array('x' => date('m-d', $start), 'y' => $number_item, 'day_in_deal' => $day_in_deal);
  if ($number_item) $total += $number_item;
}

?>

<canvas id="canvas" height="400" width="920"></canvas>
<table>
  <tbody>
    <tr><th><?php echo $this->__('Start time');?></th><td><?php echo $deal->getStartTime(); ?></td></tr>
    <tr><th><?php echo $this->__('End time');?></th><td><?php echo $deal->getEndTime(); ?></td></tr>
    <tr><th><?php echo $this->__('Total sales');?></th><td><?php echo $total.$this->__(' item(s)'); ?></td></tr>
  </tbody>
</table>
<script>

  var lineChartData = {
    labels : [
    // "January","February","March","April","May","June","July"
    <?php 
      foreach($graph as $item) {
        echo '"'.$item['x'].'",';
      }
    ?>
    ],
    datasets : [
      {
        fillColor : "rgba(205, 58, 57, 0.2",
        strokeColor : "rgba(205, 58, 57, 0.2)",
        pointColor : "rgba(205, 58, 57, 0.2)",
        data : [
        // 28,48,40,19,96,27,100
        <?php
          foreach($graph as $item) {
            echo  ($item['day_in_deal']) ? ($max_item+1).',' : '0,';
          }
        ?>
        ]
      },
      {
        fillColor : "rgba(100, 100, 236, 0.5)",
        strokeColor : "rgba(100, 100, 236, 0.9)",
        pointColor : "rgba(100, 100, 236, 0.9)",
        data : [
        // 28,48,40,19,96,27,100
        <?php
          foreach($graph as $item) {
            echo $item['y'].',';
          }
        ?>
        ]
      },
    ]
    
  }

var graph = document.getElementById("canvas").getContext("2d");

var myLine = new Chart(graph).Line(lineChartData,{
  //Boolean - If we want to override with a hard coded scale
  scaleOverride : true,
  
  //** Required if scaleOverride is true **
  //Number - The number of steps in a hard coded scale
  scaleSteps : <?php echo $max_item+1; ?>,
  //Number - The value jump in the hard coded scale
  scaleStepWidth : 1,
  //Number - The scale starting value
  scaleStartValue : 0,
});


</script>
