<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Collpur
 * @version    1.0.6
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
?>
<div class="entry-edit">
    <?php echo $this->getFormHtml(); ?>
</div>
<?php $deal = Mage::registry('collpur_deal') ?>
    <div <?php if ($this->getDisableGrid()): ?>style="display:none"<?php endif; ?> class="awcp_coupons_showhide">
    <?php echo $this->getGridHtml(); ?>
    </div>

<?php echo $this->getChildHtml('form_after'); ?>

<script type = "text/javascript">
    document.observe("dom:loaded", function() {
        $('deal_enable_coupons').observe('change',function() {
            $$('.awcp_coupons_showhide').invoke('toggle');
        });
    });
</script>
