<?php if ($this->helper('occ')->isEnabled()): ?>	
<!--[if lt IE 9]>
<style>
	/* POPUP CONTAINER */
	#occ-popup-wrapper-bkg { 	
		background:transparent;
	    filter:progid:DXImageTransform.Microsoft.gradient(startColorStr=#4c000000,endColorStr=#4c000000);
	    -ms-filter:"progid:DXImageTransform.Microsoft.gradient(startColorstr=#4c000000,endColorstr=#4c000000)";
	}	
	.popup-container .popup-content #occ-close button.button { margin-left:5px; }
</style>
<![endif]-->
<?php endif; ?>
