<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Collpur
 * @version    1.0.6
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
?>
<div class="content-header">
    <table cellspacing="0">
        <tbody><tr>
                <td style="width:50%;"><h3 class="icon-head head-adminhtml-deal"><?php echo Mage::helper('collpur')->__('Linked-to-deal product visibility'); ?></h3></td>
                <td class="form-buttons"><button onclick="prepareVisbilityParam();" class="scalable" type="button" id="next_step_deal"><span><?php echo $this->__('Next step'); ?></span></button></td>
            </tr>
        </tbody></table>
</div>
<div class="entry-edit">
    <form action="<?php echo $this->getUrl('*/*/edit',array('product_id'=>Mage::app()->getRequest()->getParam('product_id'))) ?>" method="post" id="dealStepTwoForm">
        <?php echo $this->getFormHtml(); ?>
    </form>
</div>
<?php echo $this->getChildHtml('form_after'); ?>

<script type = "text/javascript">
    function prepareVisbilityParam() {
        $('dealStepTwoForm').action += 'product_visibility/'+ $('product_visibility').value + '/'
        $('dealStepTwoForm').submit()
    }
 </script>