<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Productquestions
 * @version    1.5.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 */
?>
<?php if ($this->collection->getSize() > 0) { ?>
<ol style="list-style: none;">
    <?php foreach ($this->collection as $item) { ?>
    <li>
        <span style="padding-right: 10px;"><i><?php echo $this->getDate($item)?></i></span>
        <a href="<?php echo $this->getUrlQuestions($item)?>"><?php echo $item->getQuestionProductName()?></a><br>
        <div style="padding-bottom: 5px;"><?php echo $this->getQuestion($item);?></div>
    </li>
    <?php } ?>
</ol>
<?php } ?>