<?php
  /*
  * Copyright (c) 2014 www.magebuzz.com
  */
?>
<?php Mage::helper('dailydeal')->updateAllDealStatus(); ?>
<?php if(Mage::helper('dailydeal')->isActiveDailydeal()): ?>
  <?php $deals = Mage::helper('dailydeal')->getTodayDeals(); ?>
  <?php if($deals->getSize()):?>
    <div class="block block-deals">
      <div class="block-title"><strong><span><?php echo $this->__('Today Deals'); ?></strong></span></div>
      <div class="block-content">
        <div id="deals-table">
          <table id="deal-list">
            <?php $i=0;?>
            <?php		
              foreach($deals as $deal):
              ?>
              <tr>
                <?php $product = Mage::getModel('catalog/product')->load($deal->getProductId());?>
                <?php $now_time = Mage::getModel('core/date')->timestamp(time());?>
                <td>
                  <div class="product-deal-image">
                    <a href="<?php echo $product->getProductUrl(); ?>" title="<?php echo $product->getName(); ?>">
                      <img alt="" src="<?php echo $product->getSmallImageUrl(135,135)?>" />
                    </a>
                  </div>
                  <div class="product-deal-name">
                    <a href="<?php echo $product->getProductUrl(); ?>" title="<?php echo $product->getName(); ?>">
                      <?php echo $product->getName(); ?>
                    </a>
                  </div>
                  <div class="deal-price">
                    <div class="price-box">
                      <label><?php echo $this->__('Price:') ?></label>
                      <span class="price"><?php echo Mage::helper('core')->currency($deal->getDealPrice());?></span>
                    </div>
                  </div>
                  <div class="save-price">
										<?php $is_rounded = Mage::getStoreConfig('dailydeal/general/round_saving');?>
                    <?php $save = floatval($product->getPrice()) - floatval($deal->getDealPrice());?>
                    <?php if ($is_rounded):?>
										<?php $save = round(100 * $save / floatval($product->getPrice()),0);?>
										<?php else:?>
										<?php $save = round(100 * $save / floatval($product->getPrice()),2);?>
										<?php endif;?>
                    <label><?php echo $this->__('Save:') ?></label>
                    <span class="price"><?php echo $save; ?><?php echo $this->__('%');?></span>
                  </div>
									<?php if((Mage::getModel('core/date')->timestamp($deal->getEndTime()) > $now_time) && ($deal->getQuantity())):?>
                    <h4><?php echo $this->__('Deal Time') ?> <span id="timeleft_sidebar_<?php echo $deal->getId()?>" class="timeleft"> </span></h4>									
                    <?php $end_time = Mage::getModel('core/date')->timestamp($deal->getEndTime()); ?>
                    <script type="text/javascript">
                      //<![CDATA[
                      var dTimeCounter_<?php echo $i?> = new DealTimeCounter('<?php echo $now_time ?>', '<?php echo $end_time ?>','<?php echo $deal->getId() ?>');
                      dTimeCounter_<?php echo $i?>.setTimeleft('timeleft_sidebar_<?php echo $deal->getId()?>');
                      //
                    </script>
                    <?php endif;?>	
                  <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                </td>
                <?php $i++;?>
              </tr>
              <?php endforeach; ?>
          </table>
          <script type="text/javascript"> decorateTable('deal-list');</script>
        </div>
      </div>
    </div>
    <?php else:?>
    <p><?php echo $this->__('There is no deal available.');?></p>
    <?php endif;?>
  <?php endif;?>