<div class="block-login"> 
	<div id="occ-close"><a href="javascript:void(0);" onclick="occTools.hidePopup('occ-login',true);">close(x)</a></div>
    <div class="occ-page-title">
        <h2><?php echo $this->__('Login') ?></h2>
    </div>
    <form action="" method="post" id="login-form-validate">
        <div class="content">
			<div class="subtitle"><?php echo $this->__('If you have an account with us, please log in.') ?></div>
			<div class="form">
				<label for="mini-login" class="required"><em>*</em><?php echo $this->__('Email:') ?></label><input type="text" name="login[username]" id="mini-login" value="" class="input-text required-entry validate-email" />
				<label for="mini-password" class="required"><em>*</em><?php echo $this->__('Password:') ?></label><input type="password" name="login[password]" id="mini-password" value="" class="input-text required-entry validate-password" />
			</div>
			<div class="actions buttons-set" id="login-mini-buttons-container">
				<p class="required"><?php echo $this->__('* Required Fields') ?></p>
				<button type="button" class="button" onclick="occLogin.postLogin();"><span><span><?php echo $this->__('Login') ?></span></span></button>                
				<span class="please-wait" id="login-mini-please-wait" style="display:none;">
					<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Please wait...') ?>" title="<?php echo $this->__('Please wait...') ?>" class="v-middle" /> <?php echo $this->__('Please wait...') ?>
				</span>
			</div>
        </div>
    </form>
</div>
